# Installs npm dependencies and deploys to GH pages

name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ 12.x }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ 12.x }}
        cache: 'npm'
    - run: npm run predeploy
    - run: npm run deploy
